# Claude API key profile management

# List API key profiles from ~/.claude/profiles.json (generated by chezmoi)
def "claude profiles" [] {
    let file = ($nu.home-dir | path join ".claude" "profiles.json")
    if not ($file | path exists) {
        error make { msg: $"Missing profile registry: ($file). Run 'chezmoi apply' first." }
    }
    open $file
}

# Pick an API key and launch Claude Code with it (env scoped to the child process)
def claude-select [] {
    let choice = (claude profiles | input list --display name)
    print $"Launching Claude with key: ($choice.name) @ ($choice.base_url)"
    with-env {
        ANTHROPIC_AUTH_TOKEN: $choice.api_key
        ANTHROPIC_BASE_URL: $choice.base_url
        HTTPS_PROXY: "http://127.0.0.1:1081"
        HTTP_PROXY: "http://127.0.0.1:1081"
        NO_PROXY: "localhost,127.0.0.1,::1"
    } {
        ^claude --settings ($nu.home-dir | path join ".claude" "anyrouter.json")
    }
}
