# codex API key profile management

# List API key profiles from ~/.codex/profiles.json (generated by chezmoi)
def "codex profiles" [] {
    let file = ($nu.home-dir | path join ".codex" "profiles.json")
    if not ($file | path exists) {
        error make { msg: $"Missing profile registry: ($file). Run 'chezmoi apply' first." }
    }
    open $file
}

# Pick an API key and launch codex Code with it (env scoped to the child process)
def codex-select [] {
    let choice = (codex profiles | input list --display name)
    print $"Launching codex with key: ($choice.name) @ ($choice.base_url)"
    with-env {
        ANYROUTER_API_KEY: $choice.api_key
        HTTPS_PROXY: "http://127.0.0.1:1081"
        HTTP_PROXY: "http://127.0.0.1:1081"
        NO_PROXY: "localhost,127.0.0.1,::1"
    } {
        ^codex
    }
}
