# Pi API key profile management

# List API key profiles from ~/.pi/profiles.json (generated by chezmoi)
def "pi profiles" [] {
    let file = ($nu.home-dir | path join ".pi" "profiles.json")
    if not ($file | path exists) {
        error make { msg: $"Missing profile registry: ($file). Run 'chezmoi apply' first." }
    }
    open $file
}

# Pick an API key and launch Pi with it (env scoped to the child process)
def pi-select [] {
    let choice = (pi profiles | input list --display name)
    print $"Launching Pi with key: ($choice.name) @ ($choice.base_url)"
    with-env {
        PI_ANYROUTER_CC_API_KEY: $choice.api_key
        HTTPS_PROXY: "http://127.0.0.1:1081"
        HTTP_PROXY: "http://127.0.0.1:1081"
        NO_PROXY: "localhost,127.0.0.1,::1"
    } {
        ^pi
    }
}
