return {
   ensure_installed = {
      "bash",
      "c",
      "css",
      "gotmpl",
      "html",
      "javascript",
      "json",
      "lua",
      "luadoc",
      "markdown",
      "nu",
      "printf",
      "python",
      "query",
      "regex",
      "rst",
      "rust",
      "toml",
      "vim",
      "vimdoc",
      "yaml",
   },
   highlight = {
      enable = true,
   },
   indent = { enable = true },
}
