[net]
git-fetch-with-cli = true
retry = 10

[unstable]
gc = true

[source.crates-io]
replace-with = "rsproxy-sparse"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[http]
timeout = 600
multiplexing = false
